language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - pypy
    - pypy3
env:
  global:
    - ZOPE_INTERFACE_STRICT_IRO: 1
  jobs:
    - DEP: test
    - DEP: no_such_extra


install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls zope.testing zope.testrunner
    - pip install -U -e .[$DEP]
script:
    - coverage run -m zope.testrunner --test-path=src
after_success:
    - coveralls
notifications:
    email: false
cache: pip
